# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    env:
      # https://docs.github.com/en/actions/reference/software-installed-on-github-hosted-runners#xcode
      DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build
        run: xcodebuild
              -scheme GitHubActionsSample
              -sdk iphonesimulator 
              -configuration Debug
              build 

      - name: Run unit tests
        run: xcodebuild
              -scheme GitHubActionsSample
              -sdk iphonesimulator
              -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
              clean test
